config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :users, only: [ :index, :show, :edit, :update ]
  get :profile, to: "users#profile"
  resources :projects do
    patch :toggle_status, on: :member
    resources :reviews, only: [ :new, :create ]
    resources :applications, only: [ :new, :create, :index, :show, :destroy ]
    resources :chatrooms, only: :show do
      resources :messages, only: :create
    end
  end

  post :accept, to: "applications#accept"
  post :reject, to: "applications#reject"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
  <div class="navbar navbar-expand-sm navbar-lewagon">
    <div class="container">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logo-font-norwester-782842-removebg.png" %>
        <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto homepage-nav">
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <%= link_to '<i class="fas fa-search"></i> Projects'.html_safe, projects_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <%= link_to '<i class="fas fa-plus"></i> Project'.html_safe, new_project_path, class: "nav-link" %>
            </li>
            <% if current_user.photo.present? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "missing-avatar-female-200x200.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>

              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to root_path, class: "dropdown-item" do %>
                  <i class="fa fa-home" aria-hidden="true"></i> Home
                <% end %>
                <%= link_to profile_path, class: "dropdown-item" do %>
                  <i class="fa fa-desktop" aria-hidden="true"></i> Dashboard
                <% end %>
                <%= link_to new_project_path, class: "dropdown-item" do %>
                  <i class="fas fa-pen" aria-hidden="true" id="pen-icon"></i> Create Project
                <% end %>
                <%= link_to users_path, class: "dropdown-item" do %>
                  <i class="fa fa-users" aria-hidden="true"></i> Find Buddies
                <% end %>
                <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                  <i class="fa fa-power-off" aria-hidden="true"></i> Log out
                <% end %>
              </div>
          <% else %>

              <li class="nav-item dropdown">
                <%= link_to '<i class="fas fa-search"></i> Projects'.html_safe, projects_path, class: "nav-link" %>
              </li>
              <li class="nav-item dropdown">
                <%= link_to '<i class="fas fa-plus"></i> Project'.html_safe, new_project_path, class: "nav-link" %>
              </li>
              <li class="nav-item dropdown">
                <%= link_to "Login", new_user_session_path, class: "nav-link" %>
              </li>
              <li class="nav-item dropdown">
                <%= link_to "Sign up", new_user_registration_path, class: "btn btn-danger" %>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>