config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :users, only: [ :index, :show, :edit, :update ]
  get :profile, to: "users#profile"
  resources :projects do
    patch :toggle_status, on: :member
    resources :reviews, only: [ :new, :create ]
    resources :applications, only: [ :new, :create, :index, :show, :destroy ]
    resources :chatrooms, only: :show do
      resources :messages, only: :create
    end
  end

  post :accept, to: "applications#accept"
  post :reject, to: "applications#reject"
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :applications, dependent: :destroy
  has_many :users, through: :applications
  has_many :reviews, dependent: :destroy
  has_one :chatroom, dependent: :destroy
  has_many :messages, through: :chatroom
  has_many :project_technologies, dependent: :destroy
  has_many :technologies, through: :project_technologies
  has_rich_text :rich_content
  has_one_attached :document
  validates :title, :description, :duration, :difficulty, presence: true
  validates :title, length: { in: 10..200 }
  validates :description, length: { in: 20..1500 }
  validates :duration,  numericality: { only_integer: true, greater_than: 0 }
  # Difficulty
  DIFFICULTIES = %w(beginner intermediate advanced)
  validates :difficulty, inclusion: { in: DIFFICULTIES }
  # PG Search
  include PgSearch::Model
  pg_search_scope :search_by_title_and_description,
  against: [:title, :description],
  using: {
    tsearch: { prefix: true }
  }

  def technology_selected?(technology)
    technologies.include?(technology)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def new
    @project = Project.new
  end

  def create
  @project = Project.new(strong_params)
    @project.user = current_user
    if @project.save
      Chatroom.create(project_id: @project.id)
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def update
    @project.update(strong_params)
    if @project.save
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def edit; end

  def destroy
    @project.destroy
    redirect_to root_path
  end

  def index
    if params[:query].present?
      @projects = Project.includes([:technologies]).search_by_title_and_description(params[:query])
    elsif params.has_key?(:difficulty)
      @projects = Project.includes([:technologies]).where(difficulty: params[:difficulty])
    elsif params.has_key?(:created_at)
      if params[:created_at] == "most_recent"
        @projects = Project.includes([:technologies]).order("projects.created_at DESC")
      else
        @projects = Project.includes([:technologies]).order("projects.created_at ASC")
      end
    else
      @projects = Project.includes([:technologies]).all
    end
  end

  def show
    @technology_ids = @project.technologies.ids
    @related_projects = Project.where.not(id: @project.id).joins(:project_technologies).where(project_technologies: { technology_id: [@technology_ids] }).distinct
    @application = Application.new
    if user_signed_in?
      @applications = Application.where(project_id: @project.id, user_id: current_user.id).where.not(status: nil).first
    end
    @project_reviews = Review.where(project_id: @project.id)
  end

  def toggle_status
    @project = Project.find(params[:id])
    @project.update(status: !@project.status)
    redirect_to project_path(@project)
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def strong_params
    params.require(:project).permit(:title, :description, :rich_content, :document, :difficulty, :duration, technology_ids: [] )
  end
end

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/edit.html.erb
<div class="container mt-5">
  <%= render 'components/form_project' %>
</div>

app/views/projects/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-xs-12 col-md-10 col-lg-10 offset-lg-1">
      <div class="introduction">
        <div class="row">
          <div class="col-xs-12 col-md-9">
            <h1 class="project-title mt-3">Project Noticeboard</h1>
            <p>All projects our users create can be found here. Find a project you like, join a team of code buddies and start coding! Projects you create will also appear on this page (just another opportunity to show off). Let's get creative!</p>
            <%= render 'components/project_search' %>
          </div>
          <div class="col-md-2 sticky-note-container mt-3">
            <div class="sticky-note">
              <h2>Help needed</h2>
              <p>Amazing project available. Looking for volunteers :-)</p>
            </div>
          </div>
        </div>
      </div>
      <% if @projects.count > 0 %>
        <% if params[:query].present? %>
          <p class="mt-5" id="lighter-paragraph">We found <strong><%= pluralize(@projects.count, "project") %></strong> with <strong>"<%= params[:query] %>"</strong> in the title or description</p>
        <% end %>
        <div class="row mt-5">
          <%= render 'components/project_loop' %>
        </div>
        <% else %>
          <h4 class="mt-4">No matches found for "<%= params[:query] %>"</h4>
      <% end %>
      </div>
  </div>
</div>

app/views/projects/new.html.erb
<%= render 'components/form_project' %>

app/views/projects/show.html.erb
<% content_for :meta_title, "#{@project.title} is on #{DEFAULT_META["meta_project_name"]}" %>
<% content_for :meta_description, @project.description %>
<div class="container mt-3">

  <div class="row">
    <div class="col-xs-12 col-md-10 col-lg-10 offset-lg-1">
      <div class="title-container">
        <h1 class="project-title mt-3"><%= @project.title %></h1>
        <%# show controls if current user is project owner %>
        <%= render 'components/show_controls' %>
      </div>
      <% if user_signed_in? && current_user.id != @project.user.id %>
        <p><i class="fa fa-user"></i> Led by: <%= link_to "#{@project.user.first_name} #{@project.user.last_name}", user_path(@project.user.id) %></p>
      <% end %>
      </div>
  </div><!--end row-->

  <div class="row mt-3">
    <div class="col-xs-12 col-md-10 col-lg-10 offset-lg-1">
      <h5 class="project-main-header">About the Project</h5>
      <%= render 'components/show_project_status' %>
      <p class="project-description-paragraph"><%= @project.description %></p>
    </div>
  </div><!--end row-->

  <div class="row">
    <div class="col-sm-3 offset-lg-1 mt-3 ">
      <h6 class="project-side-header"><i class="fa fa-calendar" aria-hidden="true"></i> Estimated duration</h6>
      <p class="project-description-paragraph"><%= @project.duration %> days</p>
    </div>

    <div class="col-sm-3  mt-3 ">
      <h6 class="project-side-header"><i class="fas fa-chart-bar" id="project-show-bar-chart"></i> Difficulty level</h6>
      <p class="project-description-paragraph"> <%= @project.difficulty.capitalize %> </p>
    </div>

    <div class="col-sm-3  mt-3 ">
    <h6 class="project-side-header"><i class="fa fa-link" aria-hidden="true"></i> Project resources</h6>
      <% if @project.rich_content.body %>
        <p class="project-description-paragraph"><%= @project.rich_content %></p>
      <% else %>
        <p class="project-description-paragraph">None posted so far</p>
      <% end %>
    </div>
  </div><!--end row-->

  <div class="row mt-3">
    <div class="col-sm-3 col-lg-3 offset-lg-1 ">
      <h6 class="project-side-header">Technologies involved</h6>
        <%= render 'components/technology_icon' %>
    </div>
    <div class="col-sm-3 col-lg-3 ">
      <h6 class="project-side-header">Questions?</h6>
      <p class="project-description-paragraph"><%= link_to "Jump to this project's chat", project_chatroom_path(@project) %> to find out more.</p>
    </div>
  </div><!--end row-->



  <div class="row">
    <div class="col-xs-12 col-md-12 col-lg-10 offset-lg-1">
      <%# show reviews and related projects when user signed out %>
      <% if @project.status == true %>
        <%= render 'components/show_reviews' %>
      <% end %>

      <% if user_signed_in? %>
        <% unless current_user.id == @project.user.id %>

        <% if @applications&.pending?  %>
          <p>Awaiting response</p>

        <% elsif @applications&.rejected?  %>
          <p>I'm sorry you can't re-apply to this project</p>

          <% elsif @applications&.status.blank? && @project.status == false %>
            <%= link_to "Apply", new_project_application_path(@project.id), class: "btn btn-primary apply-button" %>

          <% elsif @applications&.accepted? %>
            <p id="double-link"><%= link_to "Jump to this project's chat", project_chatroom_path(@project) %> to find out more.</p>
          <% end %>
        <% else %>
          <h5 class="project-main-header project-buddies-header">Your project buddies</h5>
          <% if @project.applications.any? %>
            <ul>
              <%= render_users(@project.applications) %>
            </ul>
          <% else %>
            <p>This project hasn't received any applications yet</p>
          <% end %>
        <% end %>
      <% end %>
      <%= render 'components/show_related_projects' %>
    </div>
  </div><!--end row-->
</div><!--container-->

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>